# Generated by Django 4.2.1 on 2023-05-11 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=32)),
                ('grade', models.CharField(default='junior', max_length=32)),
                ('specialty', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('gamedev', 'Gamedev'), ('devops', 'Devops'), ('design', 'Design')], max_length=32)),
                ('salary', models.IntegerField(verbose_name='зарплата "от"')),
                ('experience', models.PositiveIntegerField(verbose_name='опыт работы в месяцах')),
                ('education', models.CharField(choices=[('school', 'Среднее'), ('college', 'Средне-специальное'), ('university', 'Высшее')], max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('portfolio', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
